/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppUsuariosRouteImport } from './routes/_app.usuarios'
import { Route as AppTestarAgenteRouteImport } from './routes/_app.testar-agente'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppMonitorRouteImport } from './routes/_app.monitor'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppChamadasRouteImport } from './routes/_app.chamadas'
import { Route as AppCampanhasRouteImport } from './routes/_app.campanhas'
import { Route as AppAgentesRouteImport } from './routes/_app.agentes'
import { Route as ApiPublicTwilioVoiceRouteImport } from './routes/api/public/twilio-voice'
import { Route as ApiPublicTwilioStatusRouteImport } from './routes/api/public/twilio-status'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppTestarAgenteRoute = AppTestarAgenteRouteImport.update({
  id: '/testar-agente',
  path: '/testar-agente',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitorRoute = AppMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppChamadasRoute = AppChamadasRouteImport.update({
  id: '/chamadas',
  path: '/chamadas',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasRoute = AppCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentesRoute = AppAgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicTwilioVoiceRoute = ApiPublicTwilioVoiceRouteImport.update({
  id: '/api/public/twilio-voice',
  path: '/api/public/twilio-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioStatusRoute = ApiPublicTwilioStatusRouteImport.update({
  id: '/api/public/twilio-status',
  path: '/api/public/twilio-status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/agentes': typeof AppAgentesRoute
  '/campanhas': typeof AppCampanhasRoute
  '/chamadas': typeof AppChamadasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/leads': typeof AppLeadsRoute
  '/monitor': typeof AppMonitorRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/testar-agente': typeof AppTestarAgenteRoute
  '/usuarios': typeof AppUsuariosRoute
  '/api/public/twilio-status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio-voice': typeof ApiPublicTwilioVoiceRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/agentes': typeof AppAgentesRoute
  '/campanhas': typeof AppCampanhasRoute
  '/chamadas': typeof AppChamadasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/leads': typeof AppLeadsRoute
  '/monitor': typeof AppMonitorRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/testar-agente': typeof AppTestarAgenteRoute
  '/usuarios': typeof AppUsuariosRoute
  '/': typeof AppIndexRoute
  '/api/public/twilio-status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio-voice': typeof ApiPublicTwilioVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/agentes': typeof AppAgentesRoute
  '/_app/campanhas': typeof AppCampanhasRoute
  '/_app/chamadas': typeof AppChamadasRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/monitor': typeof AppMonitorRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/testar-agente': typeof AppTestarAgenteRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/_app/': typeof AppIndexRoute
  '/api/public/twilio-status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio-voice': typeof ApiPublicTwilioVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agentes'
    | '/campanhas'
    | '/chamadas'
    | '/configuracoes'
    | '/leads'
    | '/monitor'
    | '/relatorios'
    | '/testar-agente'
    | '/usuarios'
    | '/api/public/twilio-status'
    | '/api/public/twilio-voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/agentes'
    | '/campanhas'
    | '/chamadas'
    | '/configuracoes'
    | '/leads'
    | '/monitor'
    | '/relatorios'
    | '/testar-agente'
    | '/usuarios'
    | '/'
    | '/api/public/twilio-status'
    | '/api/public/twilio-voice'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/agentes'
    | '/_app/campanhas'
    | '/_app/chamadas'
    | '/_app/configuracoes'
    | '/_app/leads'
    | '/_app/monitor'
    | '/_app/relatorios'
    | '/_app/testar-agente'
    | '/_app/usuarios'
    | '/_app/'
    | '/api/public/twilio-status'
    | '/api/public/twilio-voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicTwilioStatusRoute: typeof ApiPublicTwilioStatusRoute
  ApiPublicTwilioVoiceRoute: typeof ApiPublicTwilioVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/testar-agente': {
      id: '/_app/testar-agente'
      path: '/testar-agente'
      fullPath: '/testar-agente'
      preLoaderRoute: typeof AppTestarAgenteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitor': {
      id: '/_app/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof AppMonitorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chamadas': {
      id: '/_app/chamadas'
      path: '/chamadas'
      fullPath: '/chamadas'
      preLoaderRoute: typeof AppChamadasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campanhas': {
      id: '/_app/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof AppCampanhasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agentes': {
      id: '/_app/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AppAgentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/twilio-voice': {
      id: '/api/public/twilio-voice'
      path: '/api/public/twilio-voice'
      fullPath: '/api/public/twilio-voice'
      preLoaderRoute: typeof ApiPublicTwilioVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio-status': {
      id: '/api/public/twilio-status'
      path: '/api/public/twilio-status'
      fullPath: '/api/public/twilio-status'
      preLoaderRoute: typeof ApiPublicTwilioStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAgentesRoute: typeof AppAgentesRoute
  AppCampanhasRoute: typeof AppCampanhasRoute
  AppChamadasRoute: typeof AppChamadasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppMonitorRoute: typeof AppMonitorRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppTestarAgenteRoute: typeof AppTestarAgenteRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentesRoute: AppAgentesRoute,
  AppCampanhasRoute: AppCampanhasRoute,
  AppChamadasRoute: AppChamadasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppMonitorRoute: AppMonitorRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppTestarAgenteRoute: AppTestarAgenteRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicTwilioStatusRoute: ApiPublicTwilioStatusRoute,
  ApiPublicTwilioVoiceRoute: ApiPublicTwilioVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
