/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppMonitorRouteImport } from './routes/_app.monitor'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppCampanhasRouteImport } from './routes/_app.campanhas'
import { Route as AppAgentesRouteImport } from './routes/_app.agentes'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitorRoute = AppMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasRoute = AppCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentesRoute = AppAgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/agentes': typeof AppAgentesRoute
  '/campanhas': typeof AppCampanhasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/leads': typeof AppLeadsRoute
  '/monitor': typeof AppMonitorRoute
  '/relatorios': typeof AppRelatoriosRoute
}
export interface FileRoutesByTo {
  '/agentes': typeof AppAgentesRoute
  '/campanhas': typeof AppCampanhasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/leads': typeof AppLeadsRoute
  '/monitor': typeof AppMonitorRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/agentes': typeof AppAgentesRoute
  '/_app/campanhas': typeof AppCampanhasRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/monitor': typeof AppMonitorRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agentes'
    | '/campanhas'
    | '/configuracoes'
    | '/leads'
    | '/monitor'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agentes'
    | '/campanhas'
    | '/configuracoes'
    | '/leads'
    | '/monitor'
    | '/relatorios'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/agentes'
    | '/_app/campanhas'
    | '/_app/configuracoes'
    | '/_app/leads'
    | '/_app/monitor'
    | '/_app/relatorios'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitor': {
      id: '/_app/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof AppMonitorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campanhas': {
      id: '/_app/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof AppCampanhasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agentes': {
      id: '/_app/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AppAgentesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgentesRoute: typeof AppAgentesRoute
  AppCampanhasRoute: typeof AppCampanhasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppMonitorRoute: typeof AppMonitorRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentesRoute: AppAgentesRoute,
  AppCampanhasRoute: AppCampanhasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppMonitorRoute: AppMonitorRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
