/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppMonitorRouteImport } from './routes/_app.monitor'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppCampanhasRouteImport } from './routes/_app.campanhas'
import { Route as AppAgentesRouteImport } from './routes/_app.agentes'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitorRoute = AppMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasRoute = AppCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentesRoute = AppAgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/agentes': typeof AppAgentesRoute
  '/campanhas': typeof AppCampanhasRoute
  '/leads': typeof AppLeadsRoute
  '/monitor': typeof AppMonitorRoute
}
export interface FileRoutesByTo {
  '/agentes': typeof AppAgentesRoute
  '/campanhas': typeof AppCampanhasRoute
  '/leads': typeof AppLeadsRoute
  '/monitor': typeof AppMonitorRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/agentes': typeof AppAgentesRoute
  '/_app/campanhas': typeof AppCampanhasRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/monitor': typeof AppMonitorRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agentes' | '/campanhas' | '/leads' | '/monitor'
  fileRoutesByTo: FileRoutesByTo
  to: '/agentes' | '/campanhas' | '/leads' | '/monitor' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/agentes'
    | '/_app/campanhas'
    | '/_app/leads'
    | '/_app/monitor'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitor': {
      id: '/_app/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof AppMonitorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campanhas': {
      id: '/_app/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof AppCampanhasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agentes': {
      id: '/_app/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AppAgentesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgentesRoute: typeof AppAgentesRoute
  AppCampanhasRoute: typeof AppCampanhasRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppMonitorRoute: typeof AppMonitorRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentesRoute: AppAgentesRoute,
  AppCampanhasRoute: AppCampanhasRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppMonitorRoute: AppMonitorRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
